Repository Chromacry/ebuy-backend, pull requests merged in 2023-11, with the labels that each got.

#3 feature/get all products | Retrieving all products feature
  src/constants/GlobalConstants.mjs
  src/controllers/ProductController.mjs
  src/dao/ProductDao.mjs
  src/models/ProductModel.mjs
  src/routes/BaseRoute.mjs
  src/routes/ProductRoute.mjs
Labels: enhancement

#20 Feature/add product
  src/controllers/ProductController.mjs
  src/dao/ProductDao.mjs
  src/routes/ProductRoute.mjs
  src/utils/DateTimeUtil.mjs
  src/utils/Validations.mjs
Labels: enhancement

#24 feature/update-product
  src/controllers/ProductController.mjs
  src/dao/ProductDao.mjs
  src/routes/ProductRoute.mjs
  src/utils/RequestBodyValidationUtil.mjs
  src/utils/Validations.mjs
Labels: enhancement

#25 Feature/get product
  src/controllers/ProductController.mjs
  src/dao/ProductDao.mjs
  src/routes/ProductRoute.mjs
  src/utils/RequestBodyValidationUtil.mjs
Labels: enhancement

#26 Feature/refactoring add product and validation
  src/controllers/ProductController.mjs
  src/utils/RequestBodyValidationUtil.mjs
Labels: enhancement

#42 Bugfix/changed product to async
  src/controllers/ProductController.mjs
  src/dao/ProductDao.mjs
  src/utils/RequestBodyValidationUtil.mjs
Labels: bug

#44 Bugfix/fix validation to return
  src/utils/RequestBodyValidationUtil.mjs
Labels: bug

#45 fix: fixed condition of product validator
  src/utils/RequestBodyValidationUtil.mjs
Labels: bug

#47 Feature/dao get user
  src/controllers/ProductController.mjs
  src/dao/ProductDao.mjs
  src/dao/UserDao.mjs
Labels: enhancement

#48 feat: added unit testing for adding product
  tests/ProductController.test.mjs
Labels: enhancement

#49 fix: fixed wrong variable passed in json response in update product.
  src/controllers/ProductController.mjs
Labels: bug

#53 feat: added unit testing for update product
  tests/ProductController.test.mjs
Labels: enhancement

#55 refactor: refactored the update profile image function to use promise…
  src/controllers/UserController.mjs
Labels: enhancement

#56 feat: added unit testing (3 tests) for update profile image function
  tests/UserController.test.mjs
Labels: enhancement

#57 feat: added get all product, get one product unit test
  tests/ProductController.test.mjs
Labels: enhancement

#58 Feature/unit test user controller overall improvement
  tests/UserController.test.mjs
Labels: enhancement

#59 fix: removed sellerId from get product; changed status code to badreq…
  src/controllers/ProductController.mjs
  src/dao/ProductDao.mjs
Labels: bug

#60 feat: added check on sellerid before adding product
  src/controllers/ProductController.mjs
Labels: bug, enhancement

#61 feat: added delete product unit testing
  tests/ProductController.test.mjs
Labels: enhancement

#62 feat: created daos to be used in userController.mjs
  src/dao/UserDao.mjs
Labels: enhancement

#63 refactor: refactored all the features in the userController to use th…
  src/controllers/UserController.mjs
Labels: enhancement

#64 feat: added a timeout of 4s max
  tests/UserController.test.mjs
Labels: enhancement

#65 Bugfix/unit test product fix response message and status
  src/controllers/ProductController.mjs
  src/dao/ProductDao.mjs
  tests/ProductController.test.mjs
Labels: bug, enhancement

#66 Feature/unit test product sequence so it loops
  src/dao/UserDao.mjs
  tests/ProductController.test.mjs
Labels: enhancement

#71 Feature/added code coverage
  package.json
  tests/ProductController.test.mjs
Labels: enhancement

#73 feat: seperate validation file; comment method in model for code cove…
  src/controllers/ProductController.mjs
  src/models/ProductModel.mjs
  src/utils/ProductBodyValidationUtil.mjs
  src/utils/RequestBodyValidationUtil.mjs
Labels: enhancement

#81 feat: added 2 more test cases to register
  tests/UserController.test.mjs
Labels: enhancement
